miniBond/urls.py
from django.conf.urls import url
from django.contrib import admin
from miniBond.views import *
from django.views.generic.base import RedirectView
#,areaType,target,propertyData):
app_name = 'miniBond'
urlpatterns = [
    url(r'^$', index),
    url(r'^hello/', hello),
    url(r'^favicon.ico$', RedirectView.as_view(url=r'staticaaa/favicon.ico')),
    url(r'^refreshCache/', refreshCache),
    url(r'^myname/(\d{1,2})/$', myname),
    url(r'^index/', index, name='index'),
    url(r'^logTrace/(?P<areaType>.+)/(?P<target>.+)/(?P<propertyData>.+)/$', logTrace),
    url(r'^towx/(?P<uuid>[^/]+)/$', toWx)
]

react/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('miniBond.urls')),
]

miniBond/models.py
from django.db import models
import uuid


# Create your models here.
class Platform(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=30)
    website = models.URLField(default=' ')
    isValid = models.BooleanField(default=False)
    comments = models.CharField(max_length=30, default=" ")

    def hasvalidLinktowx(self):
        return self.linktowx and self.linktowx.isValid

    def hasvalidPromotion(self):
        return self.promotioninfo_set.filter(isValid).count() > 0

    def __str__(self):
        return self.name


class RatingOrganization(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class LabelText(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class PlatformLabel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    platForm = models.ForeignKey(Platform)
    label = models.ForeignKey(LabelText)

    def __str__(self):
        return self.platForm.name + "-" + self.label.name


class LinkToWx(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    platForm = models.OneToOneField(Platform)
    wxText = models.TextField()
    isValid = models.BooleanField(default=False)
    image = models.ImageField(
        upload_to="static/img/toWx", blank=True, null=True)
    description = models.TextField(default=" ")

    def __str__(self):
        return self.platForm.name


class PlatformRating(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    platForm = models.ForeignKey(Platform)
    ratingOrganization = models.ForeignKey(RatingOrganization)
    url = models.URLField(default='')
    ratingValue = models.CharField(max_length=10)

    def __str__(self):
        return self.ratingOrganization.name + "-" + self.platForm.name


class PromotionAgency(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class PromotionInfo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    platForm = models.ForeignKey(Platform)
    promotionAgency = models.ForeignKey(PromotionAgency)
    url = models.URLField(default='')
    isValid = models.BooleanField(default=False)
    description = models.TextField(default=" ")

    def __str__(self):
        return self.promotionAgency.name + "-" + self.platForm.name


class ClickTrace(models.Model):
    id = models.IntegerField(primary_key=True)
    cookieId = models.UUIDField()
    areaType = models.CharField(max_length=30)
    target = models.CharField(max_length=30)
    propertyData = models.CharField(max_length=30)
    clickTime = models.DateTimeField()

miniBond/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import render
from miniBond.models import *
from django.template.loader import render_to_string
import os
import uuid
from datetime import datetime


def hello(request):
    message = 'hello'
    return HttpResponse("Hello world")


def myname(request, offset):
    name = "wqfaa"
    return render(request, 'miniBond/sample.html', locals())


def index(request):
    # allpfs = Platform.objects.filter(isValid=True)
    # pfs = [p for p in allpfs if p.promotioninfo_set.filter(
    #     isValid=True).count() > 0 or (hasattr(p, 'linktowx') and p.linktowx.isValid)]
    # contextDict = {'pfs': pfs}
    templateName = "index.html"
    # staticView(contextDict, templateName, templateName)
    response = render(request, "static/"+templateName)
    if "cookieId" not in request.COOKIES:
        response.set_cookie("cookieId", uuid.uuid4())
    return response


def staticView(contextDict, templateName, staticFileName):
    static_html = 'templates/static/' + staticFileName
    if not os.path.exists(static_html):
        content = render_to_string('miniBond/' + templateName, contextDict)
        with open(static_html, 'w', encoding="utf-8") as static_file:
            static_file.write(content)


def logTrace(request, areaType, target, propertyData):
    trace = ClickTrace()
    trace.areaType = areaType
    trace.target = target
    trace.propertyData = propertyData
    trace.clickTime = datetime.now()
    cookieId = request.COOKIES[
        "cookieId"] if "cookieId" in request.COOKIES else uuid.uuid4()
    trace.cookieId = cookieId
    trace.save()

    response = HttpResponse('')
    if "cookieId" not in request.COOKIES:
        response.set_cookie("cookieId", cookieId)
    return response


def toWx(request, uuid):
    staticFileName = str(uuid)+".html"
    return render(request, "static/" + staticFileName)


def strongStaticView(contextDict, templateName, staticFileName):
    static_html = 'templates/static/' + staticFileName
    content = render_to_string('miniBond/' + templateName, contextDict)
    with open(static_html, 'w', encoding="utf-8") as static_file:
        static_file.write(content)


def refreshCache(request):
    allpfs = Platform.objects.all()
    pfs = [p for p in allpfs if
           p.promotioninfo_set.filter(isValid=True).count() > 0 or (hasattr(p, 'linktowx') and p.linktowx.isValid)]

    contextDict = {'pfs': pfs}
    templateName = "index.html"
    strongStaticView(contextDict, templateName, templateName)

    allpfs = Platform.objects.all()
    for pf in allpfs:
        if hasattr(pf, 'linktowx'):
            toWxItem = LinkToWx.objects.filter(platForm__id=pf.id).first()
            contextDict = {'wxText': toWxItem.wxText,
                           'imgName': toWxItem.image, 'pfName': toWxItem.platForm.name}

            staticFileName = str(toWxItem.platForm.id) + ".html"
            strongStaticView(contextDict, "linkToWx.html", staticFileName)

    response = HttpResponse('well done!')
    return response

react/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template.loader import get_template
from django.template import Context


def hello(request):
	message = 'hello'
	assert(False)
	return HttpResponse("Hello world")

def myname(request):
	name = "wqfaa"
	return render_to_response('sample.html', locals())

templates/miniBond/base.html
<!DOCTYPE html>
{% load staticfiles %} <!-- New line -->

<html lang="en">
<head>
	<meta name="domain_verify" content="pmrgi33nmfuw4ir2ej3gi2luouxgg33nfzrw4irmejtxk2leei5ceolegyzgcnbvmy4dcnrtgq4ginlbg5stmolbha4dqnbvgezdizrreiwce5djnvsvgylwmurdumjvgeydmnbugiytanbwg56q">
    <meta name="baidu-site-verification" content="4F0uvFJuQK" />
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/static/favicon.ico">
    <!-- <link rel="icon" href="http://getbootstrap.com/favicon.ico"> -->

    <title>什么值得投 - {% block title %}{% endblock %}</title>

    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    {% block css %}{% endblock %}
    <script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?fd1aee4a17eca29f239bbcc7f44ba2c0";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<div id="header">
    {% block header %}


    {% endblock %}
</div>

<div id="bodyContent">
    {% block content %}

    {% endblock %}
</div>


<div id="footer">
   <hr/>
   <div> Copyright © 1996-2017 All Rights Reserved. </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script> -->

<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!-- <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script> -->
{% block js %}{% endblock %}
</body>
</html>

templates/miniBond/header.html
{% load staticfiles %}
<nav class="navbar navbar-light static-top sb-navbar">
    <div class="container">
    <a href="/index">
        <img src="/static/img/vp.png" class="img-responsive" alt="Responsive image">
        <div id="navwords">  <h3>什么值得投</h3>
        <span>走的更快，也要更远...</span></div>
</a>
    </div>
</nav>

<!-- newnavtodo <nav class="navbar navbar-light static-top sb-navbar">
    <div class="container">
    <a href="/index">
        <img src="/static/img/vp.png" class="img-responsive" alt="Responsive image">
          <h3>网贷地图</h3></a>
          <div id="navwords">
            <span>网罗全网返利，剔除垃圾平台</span><span>我们要走得更快，还要更远...</span>
          </div>
    </div>
</nav> -->

<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
{#        <li data-target="#myCarousel" data-slide-to="1"></li>#}

      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
              <a href="/towx/c5bf32f3-bda1-4645-b241-39ca56ca5544/"  class="logTrace"
           data-target="wddt" data-propertydata="wddt" target="_blank">
          <img class="first-slide" src="{% static "img/banner02.jpg" %}" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              ...
            </div>

                  </div></a>
        </div>
     <!--   <div class="item">
           <a href="http://www.zhangdai360.com/index/Invite/share.html?user_code=d7ad5c9" class="logTrace"
           data-target="zdtx" data-propertydata="zdtx" target="_blank">
         <img class="first-slide" src="{% static "img/banner03.jpg" %}" alt="First slide">
           <div class="container">
           <div class="carousel-caption">
            掌贷天下 点击注册
           </div>
         </div></a>
       </div> -->

      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

templates/miniBond/index.html
{% extends "miniBond/base.html" %}
{% load staticfiles %}
{% block title %}什么值得投{% endblock %}
{% block js %}
    <script src="{% static "js/index.js" %}"></script>
{% endblock %}
{% block css %}
    <link href="{% static "css/main.css" %}" rel="stylesheet">
{% endblock %}
{% block header %}
    {% include "miniBond/header.html" %}
{% endblock %}

{% block content %}


    <div class="container-fluid" id="dataList">
        <div class="row">
           <div id='updatelabel' class="col-sm-12 col-md-8 col-md-offset-2">
            数据更新时间：2018-04-27 10:00
           </div>
            <div class="col-sm-12 col-md-8 col-md-offset-2">
                <div>
                    <form class="form-horizontal">
                        <div class="well well-lg">

                            <div class="input-group">
                                <span class="input-group-addon">搜一搜</span>
                                <input id="searchPlatform" value="" type="text" class="form-control"
                                       placeholder=" ">
                            </div>
                            <div class="input-group searchTags">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true">全部</span>
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true">上市</span>
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true">国资</span>
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true">网贷之家</span>
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true">评级</span>


                                <!--    <span class="glyphicon glyphicon-pencil" aria-hidden="true">网贷地图</span>
                                   <span class="glyphicon glyphicon-pencil" aria-hidden="true">返利网</span> -->

                            </div>
                        </div>

                    </form>

                </div>

                {% for pf in pfs %}

                        <div class="bs-callout">
                                <h4> <a class='normalwords' target="_blank" href="{{ pf.website }}">{{ pf.name }} </a></h4>
                                  {% include "miniBond/platformInfo.html" with pf=pf  %}

                                   {% if pf.linktowx and pf.linktowx.isValid  %}
                               <a class="btn btn-default  logTrace gotoInvest"
                                data-area="pinfo" data-target="{{ pf.name }}"
                               data-propertyData="vditu"
                               href="/towx/{{ pf.id }}">去 网贷地图 拿返利</a>
                                  <div class="promotionComments">
                                {{ pf.linktowx.description|linebreaks }}
                            </div>
                            {% endif %}                           

                        
                    {% for pr  in  pf.promotioninfo_set.all %}
                        {% if pr.isValid %}

                         
                                <a class="btn btn-default  logTrace gotoInvest" data-area="pinfo" data-target="{{ pf.name }}"
                                   data-propertydata="{{ pr.promotionAgency.name }}" target="_blank"
                                   href="{{ pr.url }}">去 {{ pr.promotionAgency.name }} 拿返利</a>
                            <div class="promotionComments">
                                {{ pr.description|linebreaks }}
                            </div>
                           

                        {% endif %}
                    {% endfor %}
                     </div>

                {% endfor %}

            </div>
        </div>

    </div>

{% endblock %}

templates/miniBond/linkToWx.html
{% extends "miniBond/base.html" %}
{% load staticfiles %}
{% static "" as staticUrl %}

{% block title %}{{pfName}}{% endblock %}
{% block js %}
{#    <script src="{% static "js/index.js" %}"></script>#}
{% endblock %}
{% block css %}
    <link href="{% static "css/main.css" %}" rel="stylesheet">
{% endblock %}

{% block header %}
    {% include "miniBond/header.html" %}
{% endblock %}

{% block content %}


<div class="container-fluid" >

<div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
    <h3>{{pfName}} </h3>
   
        <div class="well well-lg">
             {{ wxText|linebreaks }}
  </div>
    </div>
    <div class="col-sm-12 col-md-8 col-md-offset-2">
         <h4>交单地址：https://jinshuju.net/f/5pWW9Z</h4>
    </div>
     <div class="col-sm-12 col-md-8 col-md-offset-2">
         <img src="/{{ imgName }}" class="img-responsive" alt="Responsive image">
    </div>
</div>


</div>

{% endblock %}

templates/miniBond/platformInfo.html
         {% if pf.platformrating_set.count > 0 %}
                                    <div class="credits group">
                                        <div class="groupName">三方评级：</div>
                                        <div class="groupText">
                                            {% for credit in pf.platformrating_set.all %}
                                                <div class="creditItem">
                                                    <div class='normalwords'>
                                                        <span class="ratingOrganize">{{ credit.ratingOrganization.name }}:</span>
                                                        <span class="creditIndex"><strong>{{ credit.ratingValue }}</strong>;</span>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endif %}
                                {% if pf.comments|length >= 3 %}
                                    <div class="platformLabels group">
                                        <div class="groupName">平台标签：</div>
                                        <div class="groupText">
                                            <span class="labelItem">{{ pf.comments }}</span>
                                        </div>
                                    </div>
                                {% endif %}

templates/miniBond/sample.html
{% extends "miniBond/base.html" %}

{% block title %}Future time{% endblock %}

{% block content %}
<p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>
{% endblock %}